'use client'
import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Check,Edit3,Search,ShieldAlert,Trash2,Users} from 'lucide-react'
type T='personal'|'group'|'community'|'channel';type S='WhatsApp'|'WhatsApp Business'
type R={id:string,name:string,type:T,source:S,phone?:string,category?:string,area?:string,canSend:boolean}
const tabs:T[]=['personal','group','community','channel'];const label:{[K in T]:string}={personal:'Personal',group:'Groups',community:'Communities',channel:'Channels'}
export default function Recipients(){const [rows,setRows]=useState<R[]>([]),[tab,setTab]=useState<T>('group'),[q,setQ]=useState(''),[edit,setEdit]=useState<R|null>(null)
useEffect(()=>{setRows(JSON.parse(localStorage.getItem('jb-recipients')||'[]'))},[])
function save(x:R[]){setRows(x);localStorage.setItem('jb-recipients',JSON.stringify(x))}
function del(id:string){if(confirm('हा recipient delete करायचा?'))save(rows.filter(r=>r.id!==id))}
function dedupe(){const seen=new Set<string>();const x=rows.filter(r=>{const key=r.type==='personal'?(r.phone||'').replace(/\D/g,''):`${r.type}|${r.source}|${r.name.trim().toLowerCase()}`;if(!key||seen.has(key))return false;seen.add(key);return true});save(x);alert(`${rows.length-x.length} duplicate records removed.`)}
const view=useMemo(()=>rows.filter(r=>r.type===tab&&(!q||[r.name,r.phone,r.category,r.area].some(v=>v?.toLowerCase().includes(q.toLowerCase())))),[rows,tab,q])
return <main className="shell"><header className="topbar"><div><div className="eyebrow">JB DIGITAL</div><h1>Recipient Master</h1></div><button className="secondary" onClick={()=>location.href='/'}><ArrowLeft size={17}/> Manager</button></header><div className="type-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{label[t]}</button>)}</div><div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search recipients"/></div><button className="secondary" onClick={dedupe}><Users size={18}/> Remove Duplicates</button></div>{tab==='group'&&<div className="notice"><ShieldAlert size={18}/><div><b>Group permission review</b><span>Blocked/Admin-only group campaign मध्ये वापरला जाणार नाही.</span></div></div>}<div className="cards">{view.map(r=><article className="group-card" key={r.id}><div className="avatar">{r.name.slice(0,2).toUpperCase()}</div><div className="group-main"><div className="group-title"><h3>{r.name}</h3><span className="pill source-pill">{r.source}</span></div><p>{r.phone||[r.category,r.area].filter(Boolean).join(' · ')}</p><div className={r.canSend?'status ok':'status blocked'}>{r.canSend?'Active':'Blocked / Admin Only'}</div></div><button className="iconbtn" onClick={()=>setEdit({...r})}><Edit3 size={17}/></button><button className="iconbtn" onClick={()=>del(r.id)}><Trash2 size={17}/></button></article>)}{!view.length&&<div className="empty">No recipients found.</div>}</div>{edit&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><h2>Edit Recipient</h2><button className="iconbtn" onClick={()=>setEdit(null)}>×</button></div><label>Name<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label>{edit.type==='personal'&&<label>Phone<input value={edit.phone||''} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label>}{edit.type!=='personal'&&<><label>Category<input value={edit.category||''} onChange={e=>setEdit({...edit,category:e.target.value})}/></label><label>Area<input value={edit.area||''} onChange={e=>setEdit({...edit,area:e.target.value})}/></label></>}{edit.type==='group'&&<div className="permission-box"><b>Can you send messages in this group?</b><div className="choice-row"><button className={edit.canSend?'choice yes selected':'choice yes'} onClick={()=>setEdit({...edit,canSend:true})}>Yes</button><button className={!edit.canSend?'choice no selected':'choice no'} onClick={()=>setEdit({...edit,canSend:false})}>No / Admin only</button></div></div>}<button className="primary fullbtn" onClick={()=>{save(rows.map(r=>r.id===edit.id?edit:r));setEdit(null)}}><Check size={18}/> Save Changes</button></div></div>}</main>}
