'use client'
import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Check,Edit3,Search,ShieldAlert,Trash2,Users} from 'lucide-react'
import {supabase} from '../../lib/supabase'
type T='personal'|'group'|'community'|'channel';type S='WhatsApp'|'WhatsApp Business'
type R={id:string,name:string,type:T,source:S,phone?:string,category?:string,area?:string,canSend:boolean,link?:string}
type DBR={id:string,name:string,recipient_type:T,whatsapp_source:S,phone?:string|null,category?:string|null,area?:string|null,can_send:boolean,link?:string|null}
const tabs:T[]=['personal','group','community','channel'];const label:{[K in T]:string}={personal:'Personal',group:'Groups',community:'Communities',channel:'Channels'}
const fromDb=(r:DBR):R=>({id:r.id,name:r.name,type:r.recipient_type,source:r.whatsapp_source,phone:r.phone||undefined,category:r.category||undefined,area:r.area||undefined,canSend:r.can_send,link:r.link||undefined})
export default function Recipients(){const [rows,setRows]=useState<R[]>([]),[tab,setTab]=useState<T>('group'),[q,setQ]=useState(''),[edit,setEdit]=useState<R|null>(null),[status,setStatus]=useState('')
useEffect(()=>{void load()},[])
async function load(){if(!supabase){setStatus('Supabase configuration missing.');return}const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data,error}=await supabase.from('recipients').select('*').order('created_at',{ascending:false});if(error){setStatus(error.message);return}setRows(((data||[]) as DBR[]).map(fromDb))}
async function del(id:string){if(!confirm('हा recipient delete करायचा?')||!supabase)return;const {error}=await supabase.from('recipients').delete().eq('id',id);if(error){setStatus(error.message);return}setRows(rows.filter(r=>r.id!==id));setStatus('Recipient deleted.')}
async function dedupe(){if(!supabase)return;const seen=new Set<string>();const remove:string[]=[];for(const r of rows){const key=r.type==='personal'?(r.phone||'').replace(/\D/g,''):`${r.type}|${r.source}|${r.name.trim().toLowerCase()}`;if(!key||seen.has(key))remove.push(r.id);else seen.add(key)}if(!remove.length){setStatus('Duplicates सापडले नाहीत.');return}const {error}=await supabase.from('recipients').delete().in('id',remove);if(error){setStatus(error.message);return}setRows(rows.filter(r=>!remove.includes(r.id)));setStatus(`${remove.length} duplicate records removed.`)}
async function saveEdit(){if(!edit||!supabase)return;const {error}=await supabase.from('recipients').update({name:edit.name,phone:edit.phone||null,category:edit.category||null,area:edit.area||null,link:edit.link||null,can_send:edit.canSend,permission_status:edit.type==='group'?(edit.canSend?'verified':'adminOnly'):null,updated_at:new Date().toISOString()}).eq('id',edit.id);if(error){setStatus(error.message);return}setRows(rows.map(r=>r.id===edit.id?edit:r));setEdit(null);setStatus('Changes saved to cloud.')}
const view=useMemo(()=>rows.filter(r=>r.type===tab&&(!q||[r.name,r.phone,r.category,r.area].some(v=>v?.toLowerCase().includes(q.toLowerCase())))),[rows,tab,q])
return <main className="shell"><header className="topbar"><div><div className="eyebrow">JB DIGITAL</div><h1>Recipient Master</h1></div><button className="secondary" onClick={()=>location.href='/dashboard'}><ArrowLeft size={17}/> Dashboard</button></header>{status&&<div className="notice"><div><b>{status}</b></div></div>}<div className="type-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{label[t]}</button>)}</div><div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search recipients"/></div><button className="secondary" onClick={()=>void dedupe()}><Users size={18}/> Remove Duplicates</button></div>{tab==='group'&&<div className="notice"><ShieldAlert size={18}/><div><b>Group permission review</b><span>Blocked/Admin-only group campaign मध्ये वापरला जाणार नाही.</span></div></div>}<div className="cards">{view.map(r=><article className="group-card" key={r.id}><div className="avatar">{r.name.slice(0,2).toUpperCase()}</div><div className="group-main"><div className="group-title"><h3>{r.name}</h3><span className="pill source-pill">{r.source}</span></div><p>{r.phone||[r.category,r.area].filter(Boolean).join(' · ')}</p><div className={r.canSend?'status ok':'status blocked'}>{r.canSend?'Active':'Blocked / Admin Only'}</div></div><button className="iconbtn" onClick={()=>setEdit({...r})}><Edit3 size={17}/></button><button className="iconbtn" onClick={()=>void del(r.id)}><Trash2 size={17}/></button></article>)}{!view.length&&<div className="empty">No recipients found.</div>}</div>{edit&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><h2>Edit Recipient</h2><button className="iconbtn" onClick={()=>setEdit(null)}>×</button></div><label>Name<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label>{edit.type==='personal'&&<label>Phone<input value={edit.phone||''} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label>}{edit.type!=='personal'&&<><label>Category<input value={edit.category||''} onChange={e=>setEdit({...edit,category:e.target.value})}/></label><label>Area<input value={edit.area||''} onChange={e=>setEdit({...edit,area:e.target.value})}/></label><label>WhatsApp link<input value={edit.link||''} onChange={e=>setEdit({...edit,link:e.target.value})}/></label></>}{edit.type==='group'&&<div className="permission-box"><b>Can you send messages in this group?</b><div className="choice-row"><button className={edit.canSend?'choice yes selected':'choice yes'} onClick={()=>setEdit({...edit,canSend:true})}>Yes</button><button className={!edit.canSend?'choice no selected':'choice no'} onClick={()=>setEdit({...edit,canSend:false})}>No / Admin only</button></div></div>}<button className="primary fullbtn" onClick={()=>void saveEdit()}><Check size={18}/> Save Changes</button></div></div>}</main>}
